name: Learn CI
on:
  push:
    tags:
    - 'v*-assets*'
    - 'k8s-v*-staging*'
    - 'k8s-v*-production*'

jobs:
  my_first_job:
    runs-on: ubuntu-22.04
    if: contains(github.ref_name, 'k8s-v*-staging*' && 'k8s-v*-production*')
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

  second_job:
    if: contains(github.ref_name, 'assets')
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
